### PR TITLE
LIST(impl): Add map implementation

### PR DESCRIPTION
**Pull request by SimonMeskens**
Can I get a code review to see if these are the kinds of PRs you want? I'm versed in rebase if you need changes to the commit structure too.

### CODE REVIEW

**Comment by axefrog** [comment]
Sorry for the slow reply (Sunday and whatnot). Going to review this now. On a side note, do you by any chance have Docker set up on your local machine? Travis is failing and nobody I know can seem to reproduce the error that Travis is reporting. See: https://travis-ci.org/frptools/collectable/jobs/259185345
Apparently if you [run the Travis test instance in Docker](https://github.com/frptools/collectable/pull/48#issuecomment-314894115), it'll reproduce the issue successfully. Unfortunately my machine seems to fail when installing prerequisites for Docker, so I haven't been able to figure the issue out yet, which means that pull requests always show up as build failures.

**Comment by axefrog** [comment]
Code's all good, and builds fine for me locally. Merged. Thanks!

**Comment by SimonMeskens** [comment]
Unfortunately, Docker doesn't want to install on my machine either and I haven't been able to find out why.

Thanks for the review, I'll move on to some more challenging PRs (wanted to make sure I understood the PR process first).

**Comment by axefrog** [comment]
Travis is finally building. Your future PRs should now actually reflect this.

**Comment by SimonMeskens** [comment]
Thanks, that's helpful

**Pull request merged**
