### PR TITLE
MAIN(fix): Error when using setIn() to set a deeply nested value, fixes #55

### LINKED ISSUE #55: setIn behavior contradicts documentation
## Problem
Using `collectable@0.22.0`

It looks like `C.setIn()` tries to interact with values at times when I expect it to be interacting with keys.

See [this webpackbin for a demo](https://www.webpackbin.com/bins/-KqcsIL-Ar6MeUptLdsD).

Take special note of `map2`, which is the operation that appears to throw the type error. Copy-pasted from [the README](https://github.com/frptools/collectable#usage):

```javascript
import * as C from 'collectable';

const input = {
  foo: 'abc', <--- setIn tries to do stuff to 'abc' when it should be operating on input.foo...
  xyz: [3, [5, 6], 7, 9]
};
const map0 = C.from(input); // <{foo: 'abc', xyz: <[3, [5, 6], 7, 9]>}>
const map1 = C.updateIn(['xyz', 1, 0], n => 4, map0); // <{foo: 'abc', xyz: <[3, [4, 6], 7, 9]>}>
const map2 = C.setIn(['foo', 'bar'], x => 'baz', map1); // <{foo: <{bar: 'baz'}>, xyz: ...>

VM181 dll.js:9431 Uncaught TypeError: Cannot use 'in' operator to search for '@@is-collection' in abc
    at isCollection (VM181 dll.js:9431)
    at isIndexedCollection (VM181 dll.js:9434)
    at setDeep (VM181 dll.js:7644)
    at path.length.__WEBPACK_IMPORTED_MODULE_0__collectable_core__.IndexedCollection.updateEntry (VM181 dll.js:7647)
    at update (VM181 dll.js:9817)
    at HashMapStructure.@@update (VM181 dll.js:3664)
    at Object.updateEntry (VM181 dll.js:9425)
    at setDeep (VM181 dll.js:7647)
    at Object.setIn (VM181 dll.js:7639)
    at Object.<anonymous> (VM182 main.js:96)
```
## Desired Outcome
- [ ] If the documentation is misleading, then the example would be corrected to demonstrate the actual `setIn()` behavior. This is likely, since there are many calls for documentation throughout the project.

- [ ] If the documentation reflects the intended API correctly, then this is a bug in the implementation of `setIn()`

### PR DESCRIPTION
**Pull request by ariesshrimp**
- Includes guard that prevents isIndexedCollection() from running against primitive values
- Includes test coverage to prove deep nested writing and overwriting function

### CODE REVIEW

**Comment by ariesshrimp** [comment]
I feel like `setDeep` would make more sense if its checks were reversed.

For example, if it worked like so:

```typescript
if (not a valid collection) return fromArray()
return IndexedCollection.logic()
```

but I couldn't see a nice way of writing that. In other words, I think this is a case where the conditions should represent positive guards _against_ the non-collection path, rather than confirming the happy path.

**Comment by ariesshrimp** [comment]
Also, I took this non-primitive-check trick from here: https://stackoverflow.com/questions/31538010/test-if-a-variable-is-a-primitive-rather-than-an-object

Is there a better way to do this using Typescript powers?

**Comment by axefrog** [comment]
In `@frptools/core`, [there are the types `concrete` and `defined`](https://github.com/frptools/core/blob/master/src/types.ts#L6-L8), which are examples of how you'd do it in TypeScript. 

You could write a function like this:

```ts
type Primitive = null|undefined|string|number|boolean|symbol;
function isConcrete(value: any): value is Primitive {
  return value == Object(value); // tslint:disable-line
}
```

**Comment by axefrog** [comment]
Thanks for the pull request, the code looks good to me!

**Comment by axefrog** [comment]
New packages published.

**Pull request merged**
